- name: add group 'ben'
  group:
    name: ben
    gid: 1001
    state: present

- name: add group 'media'
  group:
    name: media
    gid: 1002
    state: present

- name: add user 'ben' and add to group 'docker'
  user:
    name: ben
    shell: /usr/bin/zsh
    uid: 1001
    group: ben
    groups: sudo,media
    append: yes

- name: add user 'media'
  user:
    name: media
    uid: 1002
    group: media
    append: yes
  
- name: add authorized keys
  authorized_key:
    user: ben
    state: present
    key: "{{ lookup('file', '~//code/ansible/provisioning/files/authorized_keys') }}"
  tags: authorized_keys