---
- name: Installing apps
  apt: pkg=acl,vim,zsh,git,curl,nfs-common,wakeonlan,python3-pip,libffi-dev,python3-dev state=latest
  register: installation
  tags:
    - install_apps

- name: install telegram-send
  pip:
    name: telegram-send

- name: Cloning oh-my-zsh for ben
  git:
    repo=https://github.com/sunch4se/oh-my-zsh
    dest=~/.oh-my-zsh
  register: cloned
  become_user: ben
  tags:
    - install_apps

- name: Create a symbolic link
  file:
    src: ~/.oh-my-zsh/.zshrc
    dest: ~/.zshrc
    state: link
  when: cloned is succeeded
  become_user: ben
  tags:
    - install_apps

- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    #cache_valid_time: 86400 #One day
  tags:
    - install_apps