---
- name: start emby
  docker_compose:
    project_src: /docker/docker-compose/emby
  register: output
  tags:
    - compose
  
- name: start hydra2
  docker_compose:
    project_src: /docker/docker-compose/hydra2
  register: output
  tags:
    - compose

- name: start sonarr-radarr-nzbget
  docker_compose:
    project_src: /docker/docker-compose/sonarr-radarr-nzbget
  register: output
  tags:
    - compose

- name: start traefik
  docker_compose:
    project_src: /docker/docker-compose/traefik
  register: output
  tags:
    - compose

- name: start tvheadend
  docker_compose:
    project_src: /docker/docker-compose/tvheadend
  register: output
  tags:
    - compose

- name: start ddclient
  docker_compose:
    project_src: /docker/docker-compose/ddclient
  register: output
  tags:
    - compose