---
- name: start traefik
  docker_compose:
    project_src: /docker/docker-compose/traefik
  register: output
  tags:
    - compose

- name: start jellyfin
  docker_compose:
    project_src: /docker/docker-compose/jellyfin
  register: output
  tags:
    - compose
  
- name: start hydra2
  docker_compose:
    project_src: /docker/docker-compose/hydra2
  register: output
  tags:
    - compose

- name: start sonarr-radarr-nzbget
  docker_compose:
    project_src: /docker/docker-compose/sonarr-radarr-nzbget
  register: output
  tags:
    - compose

- name: start tvheadend
  docker_compose:
    project_src: /docker/docker-compose/tvheadend
  register: output
  tags:
    - compose

- name: start mosquitto
  docker_compose:
    project_src: /docker/docker-compose/mosquitto
  register: output
  tags:
    - compose

- name: start home-assistant
  docker_compose:
    project_src: /docker/docker-compose/hass
  register: output
  tags:
    - compose