---
# This playbook contains all actions that will be run on "local" host.
 
# sudo apt-get update
- name: Update apt packages
  apt:
    update_cache: yes
  tags:
    - apt-update
    - system

# Import tasks
- name: Set timezone to Europe/Berlin
  timezone:
    name: Europe/Berlin
  tags:
    - timezone

- name: set hostname
  include_tasks: hostname.yml
  tags:
    - hostname

- name: add users
  include_tasks: adduser.yml

- name: install apps
  include_tasks: apps.yml
  tags:
    - install_apps

- name: add files and folder
  include_tasks: files.yml
  tags:
    - ssd
    - synch

- name: import docker tasks 
  include_tasks: docker.yml
  tags:
    - compose

- name: iptables forward chain to ACCEPT
  iptables:
    chain: FORWARD
    policy: ACCEPT
  tags:
    - iptables

- name: create cron-job for backup to nas
  include_tasks: backup.yml
  tags:
    - backup

# sudo apt-get autoclean
- name: Remove useless apt packages from the cache
  apt:
    autoclean: yes
  tags:
    - system
 
# sudo apt-get autoremove
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  tags:
    - system
