---
- name: Send magic Wake-On-Lan packet to turn on individual systems
  wakeonlan:
    mac: 00:11:32:51:85:CD
    broadcast: 192.168.188.255
  tags:
    - synch

- name: Wait for system to become reachable
  wait_for_connection:
  tags:
    - synch

- name: mount external nfs target
  mount:
    path: /backup
    src: 'nas.fritz.box:/volume1/homes/ben/backup/{{ shortname }}'
    fstype: nfs
    state: mounted
  register: nfs_mount
  tags:
    - synch

- name: synchronize container backup to local filesystem
  synchronize:
    src: /backup/docker/config/
    dest: /docker/config/
    archive: yes
    # delete: yes
  delegate_to: '{{ fqdn }}'
  when: nfs_mount is succeeded
  register: synch_complete
  tags:
    - synch

- name: unmount external nfs target
  mount:
    path: /backup
    src: nas.fritz.box:/volume1/homes/ben/backup/
    fstype: nfs
    state: unmounted
  when: synch_complete is succeeded
  tags:
    - synch