---
- name: Send magic Wake-On-Lan packet to turn on individual systems
  wakeonlan:
    mac: 00:11:32:51:85:CD
    broadcast: 192.168.188.255
  # delegate_to: localhost
  # become: yes
  tags:
    - synch

- name: Wait for system to become reachable
  wait_for_connection:
  tags:
    - synch

- name: mount external nfs target
  mount:
    path: /backup
    src: nas.fritz.box:/volume1/homes/ben/backup/
    fstype: nfs
    state: mounted
  tags:
    - synch

- name: synchronize container backup to local filesystem
  synchronize:
    src: /backup/{{ shortname }}/docker/config/
    dest: /docker/config/
    archive: yes
  delegate_to: odroid.eth0.zone
  tags:
    - synch

- name: unmount external nfs target
  mount:
    path: /backup
    src: nas.fritz.box:/volume1/homes/ben/backup/
    fstype: nfs
    state: unmounted
  tags:
    - synch
