- name: mkdir /ssd
  file:
    path: /ssd
    state: directory
    owner: media
 
- name: mkdir /docker
  file:
    path: /docker
    state: directory
    owner: ben

- name: mkdir /docker/config
  file:
    path: /docker/config
    state: directory
    owner: ben

- name: mkdir /docker/docker-compose
  file:
    path: /docker/docker-compose
    state: directory
    owner: ben

- name: Mount SSD
  mount:
    path: /ssd
    src: UUID=1a3729cd-0a9f-4538-85e7-3a6caa0326a6
    fstype: btrfs
    opts: noatime
    state: mounted
  tags:
    - ssd
