---
- name: change hostname
  hostname:
    name: '{{ shortname }}'
  tags:
    - hostname

- name: add valid IP and name to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: '{{ ip }} {{ fqdn }} {{ shortname }}'
    create: yes
  tags:
     - hostname