---
# This playbook contains all actions that will be run on "local" host.
 
# sudo apt-get update
- name: Update apt packages
  apt:
    update_cache: yes
  tags:
    - system

# Import tasks
- name: set hostname
  include_tasks: hostname.yml

- name: add users
  include_tasks: adduser.yml

- name: install apps
  include_tasks: apps.yml

- name: import docker tasks 
  include_tasks: docker.yml

- name: add files and folder
  include_tasks: files.yml

# sudo apt-get autoclean
- name: Remove useless apt packages from the cache
  apt:
    autoclean: yes
  tags:
    - system
 
# sudo apt-get autoremove
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  tags:
    - system
