all:  
  hosts:
    "rock.eth0.zone":
      ansible_connection: ssh
      ansible_user: rock64 # Remote user
      ansible_host: rock.eth0.zone # Remote host
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python3
      shortname: rock

    "odroid.eth0.zone":
      ansible_connection: ssh
      ansible_user: ben # Remote user
      ansible_host: odroid.eth0.zone # Remote host
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python3
      shortname: odroid
      fqdn: odroid.eth0.zone
      ip: '192.168.188.211'